[profile.default]
src = 'contracts'
out = 'out'
auto_detect_solc = true
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer_runs = 100000
evm_version = 'paris'
[rpc_endpoints]
default_network = "https://mainnet-rpc.nordekscan.com/"
localhost = "http://127.0.0.1:8545"

gnosis = "https://rpc.gnosischain.com"
chiado = "https://rpc.chiadochain.net"
base = "https://mainnet.base.org"
baseGoerli = "https://goerli.base.org"
nordek = "https://mainnet-rpc.nordekscan.com/"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
